name: deslizas
description: El Juego de las Palabras - Una versión móvil del juego Password
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_animate: ^4.5.0
  vibration: ^1.8.4
  fl_chart: ^0.66.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/words/
    - assets/images/ 